/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bab7;

/**
 *
 * @author LENOVO
 */
public class GUI_MenuUtama1 extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MenuUtama
     */
    public GUI_MenuUtama1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        GUI_Baru7 = new javax.swing.JMenuItem();
        GUI_Beasiswa7 = new javax.swing.JMenuItem();
        GUI_Reguler7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PROGRAM SEDERHANA PENDAFTARAN SISWA SMA");

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");

        GUI_Baru7.setText("GUI_Baru7");
        GUI_Baru7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_Baru7ActionPerformed(evt);
            }
        });
        jMenu2.add(GUI_Baru7);

        GUI_Beasiswa7.setText("GUI_Beasiswa7");
        GUI_Beasiswa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_Beasiswa7ActionPerformed(evt);
            }
        });
        jMenu2.add(GUI_Beasiswa7);

        GUI_Reguler7.setText("GUI_Reguler7");
        GUI_Reguler7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUI_Reguler7ActionPerformed(evt);
            }
        });
        jMenu2.add(GUI_Reguler7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUI_Baru7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_Baru7ActionPerformed
        // TODO add your handling code here:
        GUI_Baru7 baru = new GUI_Baru7();
        baru.show();
    }//GEN-LAST:event_GUI_Baru7ActionPerformed

    private void GUI_Beasiswa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_Beasiswa7ActionPerformed
        // TODO add your handling code here:
        GUI_Beasiswa7 beasiswa = new GUI_Beasiswa7();
        beasiswa.show();
    }//GEN-LAST:event_GUI_Beasiswa7ActionPerformed

    private void GUI_Reguler7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUI_Reguler7ActionPerformed
        // TODO add your handling code here:
        GUI_Reguler7 reguler = new GUI_Reguler7();
        reguler.show();
    }//GEN-LAST:event_GUI_Reguler7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MenuUtama1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GUI_Baru7;
    private javax.swing.JMenuItem GUI_Beasiswa7;
    private javax.swing.JMenuItem GUI_Reguler7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
